version: '2.0'
services:
  discovery-builders:
    image: wallisoncarmo/discovery-builder:v2
    container_name: discovery-builders
    ports:
      - 8761:8761
  client-service:
    image: wallisoncarmo/client-service-builders:v2
    container_name: client-service-builders
    ports:
      - 8082:8082
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      discovery-builders :
        condition: service_started
      client-postgresql:
        condition: service_started
  gateway-builders:
    image: wallisoncarmo/gateway-builders:v2
    container_name: gateway-builders
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      client-service:
        condition: service_started        
  client-postgresql:
    image: postgres:12-alpine
    container_name: bd-desafio-builders-pg12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbbuilders-client
    ports:
      - 5432:5432    
