spring:
  application:
    name: gateway
  profiles:
    active: local
server:
  port: 8080

zuul:
  routes:
    client-service:
      service-id: client-service
      path: /client-service/**
  sensitive-headers: Cookie,Set-Cookie

