spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://bd-desafio-builders-pg12:5432/dbbuilders-client
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 3

eureka:
  client:
    service-url:
      defaultZone: http://discovery-builders:8761/eureka