spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dbbuilders-client
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 3