-- Drop table

-- DROP TABLE public.tb_address;

CREATE TABLE public.tb_address (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cep varchar(8) NOT NULL,
	city varchar(100) NOT NULL,
	complement varchar(254) NULL,
	neighborhood varchar(100) NOT NULL,
	public_place varchar(100) NOT NULL,
	uf varchar(255) NOT NULL,
	CONSTRAINT tb_address_pkey PRIMARY KEY (id)
);
