-- Drop table

-- DROP TABLE public.tb_client;

CREATE TABLE public.tb_client (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cpf varchar(255) NOT NULL,
	name_client varchar(150) NULL,
	nascimento date NOT NULL,
	address_id int8 NOT NULL,
	CONSTRAINT tb_client_pkey PRIMARY KEY (id),
	CONSTRAINT fknma1100f0pgxukinshf5ab061 FOREIGN KEY (address_id) REFERENCES public.tb_address(id)
);
