version: '1'
services:
  client-postgresql:
    image: postgres:12-alpine
    container_name: bd-desafio-builders-pg12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbbuilders-client
    ports:
      - 5432:5432